WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-998929ef69b8ddc743bbaa3fd6b268cbdba91e91"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-998929ef69b8ddc743bbaa3fd6b268cbdba91e91"