WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-f423c093bcff87c6d5dcf8f15dfdc5e09e1b86f1"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-f423c093bcff87c6d5dcf8f15dfdc5e09e1b86f1"