WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-6f35a1c38af53c92f8f0a5f8def8d29d3cb8bc9e"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-6f35a1c38af53c92f8f0a5f8def8d29d3cb8bc9e"