WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-ccf79ff28cb33d2f7c446551978948e9dc770dda"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-ccf79ff28cb33d2f7c446551978948e9dc770dda"