WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-02d71b0d2231c0e6a7ede2fc58dd9a7398afcc49"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-02d71b0d2231c0e6a7ede2fc58dd9a7398afcc49"