WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-aa2b0df20c291a401a9823fec0fb6f74cd32de10"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-aa2b0df20c291a401a9823fec0fb6f74cd32de10"