WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-f6fa8feac3e27614ce7836f87110aad0ba47b3f4"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-f6fa8feac3e27614ce7836f87110aad0ba47b3f4"