WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-86808d682fc5c20f6eabfeea2b241c3044d2fe6d"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-86808d682fc5c20f6eabfeea2b241c3044d2fe6d"