WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-eb68e8f23cb6dd11e3f96a48ad6f2ef289efb3e8"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-eb68e8f23cb6dd11e3f96a48ad6f2ef289efb3e8"