WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-d8bb3c2b03d1e4ceb1a8318946a1cdb189a6bb23"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-d8bb3c2b03d1e4ceb1a8318946a1cdb189a6bb23"