WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-47b535e65642b8cb77a3d1c6a4767c878ded9d1c"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-47b535e65642b8cb77a3d1c6a4767c878ded9d1c"