WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-431d5eac1bea62ceb42fc7c024e7eb50140fbeee"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-431d5eac1bea62ceb42fc7c024e7eb50140fbeee"