WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-a822c24b08b47d66d038a5ac91477bea5278a21c"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-a822c24b08b47d66d038a5ac91477bea5278a21c"