WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-3c44ba4808100febd6725609ddb5c1cb7ff3a53d"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-3c44ba4808100febd6725609ddb5c1cb7ff3a53d"