WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-a98ab167376b5ea0670badbef74b9d9a32f1a6b7"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-a98ab167376b5ea0670badbef74b9d9a32f1a6b7"