WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-7ea9d8f69c3a7f097724df2bb4a34e379e44faf0"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-7ea9d8f69c3a7f097724df2bb4a34e379e44faf0"