WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-e4362ea61c41e2c18c1de5a64673b4676fca6988"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-e4362ea61c41e2c18c1de5a64673b4676fca6988"