WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-7546378ce19277f2de0d957f3d0edb4a3c5d20b2"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-7546378ce19277f2de0d957f3d0edb4a3c5d20b2"