WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-6c225bbba480fb248017a68904667ce7f9bbf97c"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-6c225bbba480fb248017a68904667ce7f9bbf97c"