WIREGUARD_IMAGE: "ghcr.io/jodevsa/wireguard-operator/wireguard:sha-48677139d89ea790737b858f4226ed9dfdab9bc3"
OPERATOR_IMAGE: "ghcr.io/jodevsa/wireguard-operator/operator:sha-48677139d89ea790737b858f4226ed9dfdab9bc3"