# permissions for end users to view wireguardpeers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wireguardpeer-viewer-role
rules:
- apiGroups:
  - vpn.wireguard-operator.io
  resources:
  - wireguardpeers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vpn.wireguard-operator.io
  resources:
  - wireguardpeers/status
  verbs:
  - get
